import React from 'react';
import { ScrollAnimation, StaggerContainer, StaggerItem, HoverAnimation } from '../ui/Animations';
import { DocumentTextIcon, ChatBubbleLeftRightIcon, DocumentDuplicateIcon } from '@heroicons/react/24/outline';

const AICapabilities: React.FC = () => {
  return (
    <section id="ai-tools" className="section bg-blue-50">
      <div className="container">
        <ScrollAnimation
          variant="slideUp"
          duration={0.6}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">AI-Powered Job Application Tools</h2>
          <p className="text-lg text-secondary-600 max-w-3xl mx-auto">
            Let our AI help you stand out from the competition with personalized application materials and interview preparation.
          </p>
        </ScrollAnimation>

        <StaggerContainer className="grid grid-cols-1 lg:grid-cols-3 gap-8" staggerDelay={0.2}>
          {/* Cover Letter Generator */}
          <StaggerItem variant="slideUp" className="bg-white rounded-xl shadow-lg overflow-hidden">
            <div className="bg-primary-600 p-4 flex items-center">
              <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center mr-4">
                <DocumentTextIcon className="h-6 w-6 text-primary-600" />
              </div>
              <h3 className="text-xl font-bold text-white">Cover Letter Generator</h3>
            </div>
            <div className="p-6">
              <p className="text-secondary-600 mb-6">
                Our AI analyzes the job description and your skills to create personalized cover letters that highlight your relevant experience.
              </p>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200 mb-6">
                <div className="flex justify-between items-center mb-3">
                  <p className="font-medium text-primary-700">Sample Cover Letter</p>
                  <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">AI Generated</span>
                </div>
                <p className="text-sm text-gray-600 italic">
                  "Dear Hiring Manager,<br/><br/>
                  I am excited to apply for the Senior Frontend Developer position at TechCorp. With 5+ years of experience in React development and a passion for creating intuitive user interfaces, I believe I would be a valuable addition to your team...<br/><br/>
                  [Content tailored to job description and candidate skills]"
                </p>
              </div>
              <HoverAnimation scale={1.03}>
                <a 
                  href="#try-ai-cover-letter" 
                  className="btn-primary w-full text-center block"
                >
                  Generate Cover Letter
                </a>
              </HoverAnimation>
            </div>
          </StaggerItem>

          {/* Mock Interview Questions */}
          <StaggerItem variant="slideUp" className="bg-white rounded-xl shadow-lg overflow-hidden">
            <div className="bg-primary-600 p-4 flex items-center">
              <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center mr-4">
                <ChatBubbleLeftRightIcon className="h-6 w-6 text-primary-600" />
              </div>
              <h3 className="text-xl font-bold text-white">Mock Interview Questions</h3>
            </div>
            <div className="p-6">
              <p className="text-secondary-600 mb-6">
                Practice with job-specific interview questions generated by our AI based on the position you're applying for.
              </p>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200 mb-6">
                <div className="flex justify-between items-center mb-3">
                  <p className="font-medium text-primary-700">Sample Questions</p>
                  <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">AI Generated</span>
                </div>
                <ul className="space-y-3 text-sm text-gray-600">
                  <li>• "Describe a challenging project where you had to optimize React performance. What techniques did you use?"</li>
                  <li>• "How do you approach state management in large-scale React applications?"</li>
                  <li>• "Can you explain your experience with responsive design and mobile-first development?"</li>
                  <li>• "Tell me about a time when you had to refactor a complex codebase. What was your approach?"</li>
                </ul>
              </div>
              <HoverAnimation scale={1.03}>
                <a 
                  href="#try-mock-interview" 
                  className="btn-primary w-full text-center block"
                >
                  Generate Interview Questions
                </a>
              </HoverAnimation>
            </div>
          </StaggerItem>

          {/* Resume Tailoring */}
          <StaggerItem variant="slideUp" className="bg-white rounded-xl shadow-lg overflow-hidden">
            <div className="bg-primary-600 p-4 flex items-center">
              <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center mr-4">
                <DocumentDuplicateIcon className="h-6 w-6 text-primary-600" />
              </div>
              <h3 className="text-xl font-bold text-white">Resume Tailoring</h3>
            </div>
            <div className="p-6">
              <p className="text-secondary-600 mb-6">
                Our AI analyzes job descriptions and suggests modifications to your resume to highlight the most relevant skills and experience.
              </p>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200 mb-6">
                <div className="flex justify-between items-center mb-3">
                  <p className="font-medium text-primary-700">Sample Suggestions</p>
                  <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">AI Generated</span>
                </div>
                <ul className="space-y-3 text-sm text-gray-600">
                  <li>• "Move your React project experience to the top of your work history"</li>
                  <li>• "Add more details about your experience with responsive design"</li>
                  <li>• "Include metrics about performance improvements you achieved"</li>
                  <li>• "Add keywords: TypeScript, Redux, Jest, and CI/CD"</li>
                </ul>
              </div>
              <HoverAnimation scale={1.03}>
                <a 
                  href="#try-resume-tailoring" 
                  className="btn-primary w-full text-center block"
                >
                  Tailor Your Resume
                </a>
              </HoverAnimation>
            </div>
          </StaggerItem>
        </StaggerContainer>
      </div>
    </section>
  );
};

export default AICapabilities;
